spring:
  application:
    name: callr-client-test
  main:
    web-application-type: none
    banner-mode: off

callr:
  protocol: wss
  host: localhost
  port: 8443
  path: /
  uri: ${callr.protocol}://${callr.host}:${callr.port}${callr.path}

  test:
      client:
        id: 00000000-0000-0000-0000-A736F2F2FAD1
        uri: ${callr.uri}
        ssl:
          #enabled: true
          trust-store:
            file: classpath:localhost.jks
            #type: PKCS12
            password: s3cr3t
        authentication:
          type: basic # basic, key, ssl, jwt...
          key:
            header: x-auth-secret
            secret: A6491B50-AF73-4C47-93C0-9E6AED6278DC
          basic:
            # id: 00000000-0000-0000-0000-A736F2F2FAD2
            secret: A6491B50-AF73-4C47-93C0-9E6AED6278DC
          ssl:
            key-store:
              file: classpath:localhost.jks
              #type: PKCS12
              password: s3cr3t

logging:
  level:
    root: info
    org.corefx.callr: debug
