name: callr-calculator

services:
  calculator-hub:
    container_name: calculator-hub
    image: callr/calculator-hub
    build:
      context: ../calculator-hub-host
      dockerfile: Dockerfile
    ports:
      - "9443:9443"
    healthcheck:
      test: [ "CMD-SHELL", "echo e | telnet calculator-hub 9443" ]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: always
    networks:
      - callr-calculator

  calculator-service:
    depends_on:
      calculator-hub:
        condition: service_healthy
    container_name: calculator-service
    image: callr/calculator-service
    build:
      context: ../calculator-service-host
      dockerfile: Dockerfile
    tty: true
    restart: always
    networks:
      - callr-calculator

  calculator-client:
    container_name: calculator-client
    image: callr/calculator-client
    build:
      context: ../calculator-client-host
      dockerfile: Dockerfile
    depends_on:
      calculator-hub:
        condition: service_healthy
    tty: true
    restart: always
    networks:
      - callr-calculator

networks:
  callr-calculator:
    external: true
