#!/bin/bash
docker network create callr-calculator
docker compose up --build -d
mate-terminal --tab --title="calculator-hub" -e "docker compose logs -f calculator-hub"
mate-terminal --tab --title="calculator-service" -e "docker compose logs -f calculator-service"
mate-terminal --tab --title="calculator-client" -e "docker compose logs -f calculator-client"
