spring:
  application:
    name: callr-example-calculator-service
  main:
    web-application-type: none
    banner-mode: off

callr:
  protocol: wss
  host: localhost
  port: 9443
  path: /
  uri: ${callr.protocol}://${callr.host}:${callr.port}${callr.path}

  example:
    calculator:
      service:
        id: 00000000-0000-0000-0000-A736F2F2FAD3
        uri: ${callr.uri}
        authentication:
          type: basic # basic, key, jwt...
          key:
            header: x-auth-secret
            secret: A6491B50-AF73-4C47-93C0-9E6AED6278DC
          basic:
            # id: 00000000-0000-0000-0000-A736F2F2FAD3
            secret: A6491B50-AF73-4C47-93C0-9E6AED6278DC
        ssl:
          # enabled: true
          trust-store:
            # type: PKCS12
            file: classpath:localhost.jks
            password: s3cr3t
      authorization:
        user-roles:
          00000000-0000-0000-0000-A736F2F2FAD3:
            - adder
          00000000-0000-0000-0000-A736F2F2FAD4:
            - adder
            - divider
logging:
  level:
    root: error
    org.corefx.callr: debug
