name: callr

services:
  callr-hub:
    container_name: callr-hub
    image: callr/callr-hub
    build:
      context: ../callr-hub-host
      dockerfile: Dockerfile
    ports:
      - "8443:8443"
    healthcheck:
      test: [ "CMD-SHELL", "echo e | telnet callr-hub 8443" ]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: always
    networks:
      - callr

  callr-client:
    container_name: callr-client
    image: callr/callr-client
    build:
      context: ../callr-client-host
      dockerfile: Dockerfile
    depends_on:
      callr-hub:
        condition: service_healthy
    tty: true
    restart: always
    networks:
      - callr

networks:
  callr:
    external: true
