name: callr

services:
  callr-hub:
    container_name: callr-hub
    build:
      context: ../callr-hub-host
      dockerfile: Dockerfile
    image: callr/callr-hub
    ports:
      - "8443:8443"
    restart: always
    networks:
      - callr

  callr-client:
    depends_on:
      - callr-hub
    container_name: callr-client
    tty: true
    build:
      context: ../callr-client-host
      dockerfile: Dockerfile
    image: callr/callr-client
    restart: always
    networks:
      - callr
      
networks:
  callr:
    external: true
